title: Ben Papadopoulos
author: Ben Papadopoulos
email: bpapadopoulos@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. student, GSI, sociolinguistic researcher
theme: minima
# social links
github_username:  benpapadopoulos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
